[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "biomesh"
version = "0.6.1"
authors = [
  { name="The biomesh Authors" },
]
description = "Create meshes from segmented imaging data for finite element simulations using Gmsh."
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent"
]
dependencies = [
    "numpy>=1.26.4",
    "python-utils>=2.3.0",
    "meshio>=5.3.5, <6",
    "loguru>=0.7.2",
    "tqdm==4.66.5",
    "PyYAML>=6.0.0, <7",
    "scipy",
    "lnmmeshio>=5.6.4",
    "symfem==2025.6.0",
]

[project.urls]
"Homepage" = "https://github.com/TUM-LNM/biomesh"
"Bug Tracker" = "https://github.com/TUM-LNM/biomesh/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/biomesh"]

[tool.ruff.lint.per-file-ignores]
"src/biomesh/__init__.py" = ["F401"]
